spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jd?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/jingdong/mapper/*.xml
  type-aliases-package: org.lanqiao.jingdong.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper: debug
